export const GET_ADMIN_ORDERS_REQUEST = 'GET_ADMIN_ORDERS_REQUEST'
export const GET_ADMIN_ORDERS_SUCCESS = 'GET_ADMIN_ORDERS_SUCCESS'
export const GET_ADMIN_ORDERS_FAILURE = 'GET_ADMIN_ORDERS_FAILURE'
export const GET_ADMIN_ORDERS_RESET = 'GET_ADMIN_ORDERS_RESET'

export const GET_ADMIN_ORDERS_DETAIL_REQUEST = 'GET_ADMIN_ORDERS_DETAIL_REQUEST'
export const GET_ADMIN_ORDERS_DETAIL_SUCCESS = 'GET_ADMIN_ORDERS_DETAIL_SUCCESS'
export const GET_ADMIN_ORDERS_DETAIL_FAILURE = 'GET_ADMIN_ORDERS_DETAIL_FAILURE'
export const GET_ADMIN_ORDERS_DETAIL_RESET = 'GET_ADMIN_ORDERS_DETAIL_RESET'
