export const GET_ADMIN_SLIDE_REQUEST = 'GET_ADMIN_SLIDE_REQUEST'
export const GET_ADMIN_SLIDE_SUCCESS = 'GET_ADMIN_SLIDE_SUCCESS'
export const GET_ADMIN_SLIDE_FAILURE = 'GET_ADMIN_SLIDE_FAILURE'
export const GET_ADMIN_SLIDE_RESET = 'GET_ADMIN_SLIDE_RESET'

export const CREATE_ADMIN_SLIDE_REQUEST = 'CREATE_ADMIN_SLIDE_REQUEST'
export const CREATE_ADMIN_SLIDE_SUCCESS = 'CREATE_ADMIN_SLIDE_SUCCESS'
export const CREATE_ADMIN_SLIDE_FAILURE = 'CREATE_ADMIN_SLIDE_FAILURE'
export const CREATE_ADMIN_SLIDE_RESET = 'CREATE_ADMIN_SLIDE_RESET'

export const DELETE_SLIDE_REQUEST = 'DELETE_SLIDE_REQUEST'
export const DELETE_SLIDE_SUCCESS = 'DELETE_SLIDE_SUCCESS'
export const DELETE_SLIDE_FAILURE = 'DELETE_SLIDE_FAILURE'
export const DELETE_SLIDE_RESET = 'DELETE_SLIDE_RESET'
